### ISSUE TITLE
Multiple Sites / Domains?

### ISSUE THREAD

**Issue by YodasMyDad** [scyllagroup/UmbracoFlare#1]
Will this package support an install with multiple sites/ different hostnames?

**Comment by LoganPeck** [comment]
The way UmbracoFlare currently works is that it takes the current url that you are in the backoffice with and ignores the culture/hostnames settings in Umbraco. So without navigating to the backoffice from your other hostname, it is currently not possible. I will say though that the code is there to do it because I was initially thinking that we should go off of the culture/hostnames set in the backoffice. We are currently working on version 2.0 right now. We will really consider reintegrating that functionality. Then when purging the entire site, static files, and urls, we can have a drop down where you select the current registered hostnames in Umbraco. Any suggestions are welcome.

**Comment by YodasMyDad** [comment]
It's just you have a right click menu on a node to clear cache, and if a site has multiple domains and you just grab the url they are logged in with then you 'could' be clearing a cache for a page that doesn't exist (Not all sites could have the same pages) and some people even login on restricted/editor only domains - So on the main site you can't even get to /umbraco/ for security.

A quick/harsh approach could be to just get the node Url with the domain of the backoffice, then also loop through the umbracoDomains table and clear the cache for all domains listed. This would get everything ;)

Great package by the way, I was going to write our own. But will use this when it supports host names set on the Umbraco nodes.

**Comment by LoganPeck** [comment]
Yep, excellent points. We will make the changes and will have this support in v2 (in a few weeks). Thanks for the kind words and suggestions. Also, we were at uWestFest and listened to your talk on Merchello. It looks awesome and we will be using it in the future!

**Comment by jmcaveney** [comment]
Two thoughts on this:

1) We're using IPublishedContent.UrlWithDomain on the publishing/cache clearing but we could very easily just hook into the UrlProvider and get all the domain specific urls for each node. Don't think that's a v2 feature but could be done for a minor release. Here's the code in question:
https://github.com/scyllagroup/UmbracoFlare/blob/master/UmbracoFlare/ApiControllers/CloudflareUmbracoApiController.cs#L292

2) The other issue that presents is what to do about static urls and the url entry/wildcard cache clearing in the backoffice umbracoflare section, but I think that could be solved with a domain picker dialog when you click the button to clear. 

We can do number 1 quickly, but 2 may take a few days to hammer out the UI.

**Comment by LoganPeck** [comment]
@YodasMyDad Version 1.1.0 is up on our.umbraco and NuGet. It supports what we were talking about in this thread. Check it out and let me know how it works for you.

**Comment by YodasMyDad** [comment]
Awesome thanks. We are going to use it on an upcoming project. Will test it as soon as I can.
